Controllers/LoginController.cs
using System;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Task_Management_System2.Models;

namespace Task_Management_System2.Controllers
{
    public class LoginController : Controller
    {
        string ConnectionStringSettings = ConfigurationManager.ConnectionStrings["ConnectionString"].ToString();
        // GET: Loginc
        [HttpGet]
        public ActionResult Index()
        {
            LoginEntity user = new LoginEntity();
            return View(user);
        }

        [HttpPost]
        public ActionResult Index(LoginEntity m)
        {
            SqlConnection conn = new SqlConnection(ConnectionStringSettings);
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }

            SqlCommand selectCommand = new SqlCommand("SELECT Employee_Id ,FirstName, Password, UserType FROM Tarun_TaskManagementSystemReg WHERE Employee_Id = @Employee_Id and IsDeleted = 0 ", conn);
            selectCommand.Parameters.AddWithValue("@Employee_Id", m.Employee_Id);

            SqlDataReader reader = selectCommand.ExecuteReader();
            {
                if (reader.Read())
                {
                    int Employee_IdStored = Convert.ToInt32(reader["Employee_Id"]);
                    string storedPassword = Convert.ToString(reader["Password"]);
                    string FirstNameStored= Convert.ToString(reader["FirstName"]);
                    string UsertypeStored = Convert.ToString(reader["UserType"]);
                    string UsertypeLogin = "User";

                    if (m.Password == storedPassword && UsertypeStored== UsertypeLogin)
                    {
                        Session["Employee_IdUser"] = Employee_IdStored;
                        Session["FirstNameUser"] = FirstNameStored;

                        return RedirectToAction("DashUser");

                    }
                }
            }
           
            if (conn.State == ConnectionState.Open)
            {
                conn.Close();
            }
            return View();

        }
        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ForgotPassword(ForgetPassword m)
        {
            
            MailMessage msg = new MailMessage();
            msg.From = new MailAddress("tarun@concept.co.in");
            msg.To.Add(m.Email);
            string url = "http://localhost:60880/Login/ChangePassword?EncryptedEmail=" + HttpUtility.UrlEncode(Encrypt(m.Email));
            msg.Subject = "Forget Password Mail";
            msg.Body = "Click Here To Change Your Password : " + url;
            Session["url"] = url;
            msg.IsBodyHtml = true;

            SmtpClient smt = new SmtpClient();
            smt.Host = "mail.concept.co.in";
            smt.Port = 25;
            smt.Send(msg);
            ModelState.Clear();
            return RedirectToAction("Index");
        }
        public ActionResult ChangePassword(string EncryptedEmail)
        {
            ForgetPassword ob = new ForgetPassword();
            ob.Email = Decrypt(HttpUtility.UrlDecode(EncryptedEmail));
            return View(ob);
        }
        [HttpPost]
        public ActionResult ChangePassword(ForgetPassword m)
        {
            
            SqlConnection conn = new SqlConnection(ConnectionStringSettings);
            conn.Open();

            SqlCommand selectCommand = new SqlCommand("Update Tarun_TaskManagementSystemReg set Password = @Password WHERE Email = @Email", conn);
            
            selectCommand.Parameters.AddWithValue("@Email", m.Email);
            selectCommand.Parameters.AddWithValue("@Password", m.NewPassword);
            selectCommand.ExecuteNonQuery();
            selectCommand.Dispose();
            conn.Close();
            Session.Clear();
            Session.Abandon();
            return View("Index");
        }

        private string Encrypt(string stringToEncrypt)
        {
            byte[] inputByteArray = Encoding.UTF8.GetBytes(stringToEncrypt);
            byte[] rgbIV = { 0x21, 0x43, 0x56, 0x87, 0x10, 0xfd, 0xea, 0x1c };
            byte[] key = { };
            try
            {
                key = System.Text.Encoding.UTF8.GetBytes("A0D1nX0Q");
                DESCryptoServiceProvider des = new DESCryptoServiceProvider();
                MemoryStream ms = new MemoryStream();
                CryptoStream cs = new CryptoStream(ms, des.CreateEncryptor(key, rgbIV), CryptoStreamMode.Write);
                cs.Write(inputByteArray, 0, inputByteArray.Length);
                cs.FlushFinalBlock();
                return Convert.ToBase64String(ms.ToArray());
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }
        private string Decrypt(string EncryptedText)
        {
            byte[] inputByteArray = new byte[EncryptedText.Length + 1];
            byte[] rgbIV = { 0x21, 0x43, 0x56, 0x87, 0x10, 0xfd, 0xea, 0x1c };
            byte[] key = { };

            try
            {
                key = System.Text.Encoding.UTF8.GetBytes("A0D1nX0Q");
                DESCryptoServiceProvider des = new DESCryptoServiceProvider();
                inputByteArray = Convert.FromBase64String(EncryptedText);
                MemoryStream ms = new MemoryStream();
                CryptoStream cs = new CryptoStream(ms, des.CreateDecryptor(key, rgbIV), CryptoStreamMode.Write);
                cs.Write(inputByteArray, 0, inputByteArray.Length);
                cs.FlushFinalBlock();
                System.Text.Encoding encoding = System.Text.Encoding.UTF8;
                return encoding.GetString(ms.ToArray());
            }
            catch (Exception e)
            {
                return e.Message;
            }
        }


        [HttpGet]
        public ActionResult DashUser()
        {
            int EmplyeeId = (int)Session["Employee_IdUser"];


            SqlConnection connection = new SqlConnection(ConnectionStringSettings);
            connection.Open();

            SqlCommand command = new SqlCommand("Tarun_TaskManagementSystemReg_SelectDelete", connection);
            command.CommandType = CommandType.StoredProcedure;
            command.Parameters.AddWithValue("@Action", "SELECT");
            command.Parameters.AddWithValue("@Employee_Id", EmplyeeId);
            command.CommandType = System.Data.CommandType.StoredProcedure;
            SqlDataReader dr = command.ExecuteReader();
            Models.UserDashBoardEntity objReg = new Models.UserDashBoardEntity();

            while (dr.Read())
            {
                objReg.Employee_Id = EmplyeeId;
                objReg.FirstName = dr["FirstName"].ToString();
                objReg.LastName = dr["LastName"].ToString();
                objReg.Date_of_Birth = (dr["Date_of_Birth"].ToString());
                objReg.Address = dr["Address"].ToString();
                objReg.Phone = dr["Phone"].ToString();
                objReg.Email = dr["Email"].ToString();

            }
            connection.Close();
            return View(objReg);
        }

        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();
            return RedirectToAction("Index");
        }


    }
}

Controllers/TaskUserController.cs
using Rotativa;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task_Management_System2.Models;

namespace Task_Management_System2.Controllers
{
    public class TaskUserController : Controller
    {
        string ConnectionStringSettings = ConfigurationManager.ConnectionStrings["ConnectionString"].ToString();
        // GET: TaskUser
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UserTask()
        {
            int ID = (int)Session["Employee_IdUser"];

            SqlConnection connection = new SqlConnection(ConnectionStringSettings);
            connection.Open();

            List<TaskUserData> objlst = new List<TaskUserData>();
            SqlCommand command = new SqlCommand("Tarun_TaskManagementSystemTask_SelectDelete", connection);
            command.Parameters.AddWithValue("@Action", "SELECT ALL TASK USER");
            command.Parameters.AddWithValue("@Employee_Id", ID);
            command.CommandType = System.Data.CommandType.StoredProcedure;
            SqlDataReader dr = command.ExecuteReader();

            TaskUserData objTask = null;

            while (dr.Read())
            {
                objTask = new TaskUserData();

                objTask.TaskId = int.Parse(dr["TaskId"].ToString());
                objTask.TaskName = dr["TaskName"].ToString();
                objTask.ProjectName = dr["ProjectName"].ToString();
                objTask.ProjectId = dr["ProjectId"].ToString();
                objTask.TaskDescription = dr["TaskDescription"].ToString();
                objTask.StartDate = dr["StartDate"].ToString();
                objTask.EstimateDate = dr["EstimateDate"].ToString();
                objTask.Attachment = dr["Attachment"].ToString();
                objTask.AssignedTo = dr["AssignedTo"].ToString();
                objTask.UserComment = dr["UserComment"].ToString();
                objTask.TaskPriority = dr["TaskPriority"].ToString();
                objTask.TaskProjectHours = dr["TaskProjectHours"].ToString();

                
                objlst.Add(objTask);
            }
            return View(objlst);
        }

        

        public ActionResult CommentUser(string id)
        {
            SqlConnection conn = new SqlConnection(ConnectionStringSettings);
            conn.Open();

            SqlCommand comma = new SqlCommand("Select UserComment FROM Tarun_AddTask where TaskId=@TaskId", conn);
            comma.Parameters.AddWithValue("@TaskId", Convert.ToInt32(id));
            SqlDataReader drrr = comma.ExecuteReader();
            Comment ob = new Comment();

            while (drrr.Read())
            {
                ob.UserComment = drrr["UserComment"].ToString();
            }
            ob.TaskId = Convert.ToInt32(id);
            conn.Close();
            return View(ob);

        }
        [HttpPost]
        public ActionResult CommentUser(Comment m)
        {
            
                SqlConnection connection = new SqlConnection(ConnectionStringSettings);
                connection.Open();
                SqlCommand command = new SqlCommand("UPDATE Tarun_AddTask SET UserComment=@UserComment WHERE TaskId=@TaskId", connection);

                command.Parameters.AddWithValue("@TaskId", m.TaskId);
                command.Parameters.AddWithValue("@UserComment", m.UserComment);
                command.ExecuteNonQuery();
                connection.Close();
            
            return RedirectToAction("UserTask");
        }
        public ActionResult GeneratePdfTask()
        {
            int ID = (int)Session["Employee_IdUser"];
            SqlConnection connection = new SqlConnection(ConnectionStringSettings);
            connection.Open();

            List<TaskUserData> objlst = new List<TaskUserData>();
            SqlCommand command = new SqlCommand("Tarun_TaskManagementSystemTask_SelectDelete", connection);
            command.Parameters.AddWithValue("@Action", "SELECT ALL TASK USER");
            command.Parameters.AddWithValue("@Employee_Id", ID);
            command.CommandType = System.Data.CommandType.StoredProcedure;
            SqlDataReader dr = command.ExecuteReader();

            TaskUserData objTask = null;

            while (dr.Read())
            {
                objTask = new TaskUserData();

                objTask.TaskId = int.Parse(dr["TaskId"].ToString());
                objTask.TaskName = dr["TaskName"].ToString();
                objTask.ProjectName = dr["ProjectName"].ToString();
                objTask.ProjectId = dr["ProjectId"].ToString();
                objTask.TaskDescription = dr["TaskDescription"].ToString();
                objTask.StartDate = dr["StartDate"].ToString();
                objTask.EstimateDate = dr["EstimateDate"].ToString();
                objTask.Attachment = dr["Attachment"].ToString();
                objTask.AssignedTo = dr["AssignedTo"].ToString();
                objTask.UserComment = dr["UserComment"].ToString();
                objTask.TaskPriority = dr["TaskPriority"].ToString();

                objlst.Add(objTask);
            }
            return new PartialViewAsPdf("GeneratePdfTask", objlst)
            {
                PageOrientation = Rotativa.Options.Orientation.Landscape,
                PageSize = Rotativa.Options.Size.A4,
                CustomSwitches = "--footer-center \" [page] Page of [toPage] Pages\" --footer-line --footer-font-size \"9\" --footer-spacing 5 --footer-font-name \"calibri light\"",
                FileName = "YourTaskList.pdf"
            };
        }
        
        
        public ActionResult ForwardUser(string id)
        {
            SqlConnection connection = new SqlConnection(ConnectionStringSettings);
            connection.Open();

            List<ForwardTaskk> UpdateEmployeeList = new List<ForwardTaskk>();

            SqlCommand a = new SqlCommand("Select Employee_Id, FirstName,LastName from Tarun_TaskManagementSystemReg where IsDeleted=0", connection);

            SqlDataReader drrr = a.ExecuteReader();

            ForwardTaskk ob = null;
            while (drrr.Read())
            {
                ob = new ForwardTaskk();

                ob.Forwarded_Employee_Id = int.Parse(drrr["Employee_Id"].ToString());
                ob.FirstName = drrr["FirstName"].ToString();
                ob.LastName = drrr["LastName"].ToString();

                UpdateEmployeeList.Add(ob);

            }
            drrr.Close();
            a.Dispose();

            ForwardTaskk obb = obb = new ForwardTaskk();
            obb.TaskId = int.Parse(id);
            ViewBag.UpdateEmployeeList = UpdateEmployeeList;
            return View(obb);
        }
        [HttpPost]
        public ActionResult ForwardUser(ForwardTaskk m)
        {
            SqlConnection connection = new SqlConnection(ConnectionStringSettings);
            connection.Open();
            SqlCommand command = new SqlCommand("Tarun_Forward", connection);
            command.CommandType = CommandType.StoredProcedure;
            command.Parameters.AddWithValue("@TaskId", m.TaskId);
            command.Parameters.AddWithValue("@Employee_Id", m.Forwarded_Employee_Id);
            command.ExecuteNonQuery();
            connection.Close();
            return RedirectToAction("UserTask");
        }


        //Action For Add Hours in Task
        public ActionResult AddUser(string Task_Id,string Project_Id)
        {
            
            SqlConnection connection = new SqlConnection(ConnectionStringSettings);
            connection.Open();
            SqlCommand command = new SqlCommand("select ProjectHours  from TarunTMG_Project where ProjectId = @ProjectId ", connection);
            command.Parameters.AddWithValue("@ProjectId", Project_Id);
            SqlDataReader drrr = command.ExecuteReader();
            AddHours ob = null;
            while (drrr.Read())
            {
                ob = new AddHours();

                
                ob.TotalHours = drrr["ProjectHours"].ToString();
                ob.TaskId = Task_Id;
                ob.ProjectId = Project_Id;
            }
            drrr.Close();
            command.Dispose();
            connection.Close();

            return View(ob);
        }
        [HttpPost]
        public ActionResult AddUser(AddHours m)
        {
            SqlConnection connection = new SqlConnection(ConnectionStringSettings);
            connection.Open();
            SqlCommand command = new SqlCommand("TarunAddHoursTask", connection);

            // This SP Has A Problem TarunAddHoursTask

            command.CommandType = CommandType.StoredProcedure;
            command.Parameters.AddWithValue("@Action", "ADDHOURS");
            command.Parameters.AddWithValue("@TaskId", m.TaskId);
            command.Parameters.AddWithValue("@TaskProjectHours", m.AddHour);
            command.Parameters.AddWithValue("@ProjectId", m.ProjectId);
            command.ExecuteNonQuery();
            connection.Close();
            return RedirectToAction("UserTask");
        }
    }
}

Views/Login/ChangePassword.cshtml
@model Task_Management_System2.Models.ForgetPassword

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <style type="text/css">
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        #background {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(to right, #3498db, #2c3e50);
            z-index: -1;
        }

        form {
            margin: 50px auto;
            max-width: 400px;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        label {
            font-size: 1.2em;
            color: #333;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 1em;
        }

        .show-password {
            display: flex;
            align-items: center;
            margin-top: 10px;
        }

            .show-password input {
                margin-right: 5px;
            }

        .error-message {
            color: red;
        }

        #Button1 {
            background-color: #3498db;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1.2em;
        }

            #Button1:hover {
                background-color: #2980b9;
            }
    </style>
</head>
<body>
    @using (Html.BeginForm("ChangePassword", "Login", FormMethod.Post))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div>
            <div class="auto-style1">
                <div>
                    <div colspan="6" style="text-align: center; vertical-align: top">
                        @Html.LabelFor(model => model.NewPassword, "Change Your Password", new { @class = "control-label", @style = "font-weight: bold; font-size: xx-large; text-decoration: underline" })
                    </div>
                </div>
                <div>
                    <div style="text-align: center">
                        @Html.HiddenFor(model => model.Email)
                        @Html.LabelFor(model => model.NewPassword, "New Password:", new { @class = "control-label", @style = "font-size: x-large" })
                        @Html.PasswordFor(model => model.NewPassword, new { @class = "form-control", @style = "font-size: x-large", @type = "password" })
                    </div>
                </div>

                <div style="text-align: center">
                    <button id="Button1" type="submit" class="btn btn-primary" style="font-size: x-large">Confirm</button>
                </div>
            </div>
        </div>
    }
</body>
</html>

Views/Login/DashUser.cshtml
@model Task_Management_System2.Models.UserDashBoardEntity
@{

    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Task Management System</title>
</head>
<body>
    <div>
        <table style="width: 100%; height: 100%; z-index: 102; left: 0px; position: absolute; top: 0px;">
            <tr>
                <td colspan="2" style="height: 141px; background-color: black;">
                    <h2 align="center">
                        <span style="font-size: 32pt; color: window; font-family: Verdana;background-color: #040000;">Task Management System</span>
                    </h2>
                </td>
            </tr>
            <tr>
                <td style="BACKGROUND: gainsboro;">
                    <ul style="margin-top: 62%;">
                        <li>
                            Project
                            <ul>
                                <li style="color: black;">@Html.ActionLink("All Project", "UserProject", "Dashboard")</li>
                            </ul>
                        </li>
                        <li>
                            Task
                            <ul>
                               
                                <li style="color: black;">@Html.ActionLink("Your Tasks", "UserTask", "TaskUser")</li>

                            </ul>
                        </li>

                    </ul>
                    @Html.ActionLink("Log Out", "LogOut", "Login", null, new { style = "z-index: 101; left: 20px; position: absolute; top: 242px; color: #284E98;margin-left: 6%;" })
                    
                </td>
                <td style="width: 1090px;height: 522px;" valign="top">

                    <span style="font-size: 26pt;color: window;font-family: Verdana;flood-color: #040000;background-color: dimgray;display: table;margin: 0 auto;margin-top: 15px;"> Welcome User</span>

                    <br />

                    <dl class="dl-horizontal" style="margin-left: 100px;margin-top: 40px;font-size: medium;">
                        <dt>
                            @Html.DisplayNameFor(model => model.Employee_Id)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Employee_Id)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.FirstName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.FirstName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.LastName)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.LastName)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Date_of_Birth)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Date_of_Birth)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Email)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Email)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Address)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Address)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Phone)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Phone)
                        </dd>

                    </dl>
                </td>
            </tr>
        </table>
    </div>
</body>
</html>

Views/Login/ForgotPassword.cshtml
@model Task_Management_System2.Models.ForgetPassword

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title></title>
    <style type="text/css">
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }

        #background {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(to right, #3498db, #2c3e50);
            z-index: -1;
        }

        form {
            margin: 50px auto;
            max-width: 400px;
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        table {
            width: 100%;
            text-align: center;
        }

        label {
            font-size: 1.2em;
            color: #333;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 1em;
        }

        .show-password {
            display: flex;
            align-items: center;
            margin-top: 10px;
        }

            .show-password input {
                margin-right: 5px;
            }

        .error-message {
            color: red;
        }

        #ForgetPasswordBttn {
            background-color: #3498db;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 1.2em;
        }

            #ForgetPasswordBttn:hover {
                background-color: #2980b9;
            }
    </style>
</head>
<body>
    @using (Html.BeginForm("ForgotPassword", "Login", FormMethod.Post))
    {
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div style="text-align: center">
            @Html.LabelFor(model => model.Email, "UserId (Email) :", new { @class = "control-label", @style = "font-size: larger" })
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @style = "font-size: larger" })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
        <div style="text-align: center">
            @Html.Label("Label2", "Don't Remember Your Password!!")
            <br />
            <button id="ForgetPasswordBttn" type="submit" class="btn btn-primary" style="font-size: larger">Forget Password</button>
        </div>
    }
</body>
</html>

Views/Login/Index.cshtml
@model Task_Management_System2.Models.LoginEntity

@{
    ViewBag.Title = "Index";
    Layout = null;
}

<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f5f5f5;
    }

    .login-container {
        text-align: center;
        margin-top: 50px;
    }

    .form-container {
        max-width: 400px;
        margin: 0 auto;
        padding: 20px;
        background-color: #ffffff;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }

        .form-container h4 {
            margin-top: 0;
            font-size: 24px;
            font-weight: bold;
        }

    .form-group {
        margin-bottom: 20px;
    }

    .control-label {
        display: block;
        font-weight: bold;
        margin-bottom: 5px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
    }

    .btn {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }

    .btn-primary {
        background-color: #007bff;
        color: #fff;
    }

        .btn-primary:hover {
            background-color: #0056b3;
        }
    .forgot-password {
        text-decoration: none;
        color: #007bff;
        font-size: 14px;
        margin-top: 10px;
        display: inline-block;
    }
</style>
<h2 style="text-align: center; font-size: 36px;">Task Managemernt System</h2>


<div class="login-container">
    @using (Html.BeginForm())
    {


        <div class="form-container">
            <h4 style="center;font-size: xx-large;">User Login</h4>
            <br />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Employee_Id, htmlAttributes: new { @class = "control-label col-md-2" })

                @Html.TextBoxFor(model => model.Employee_Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Employee_Id, "", new { @class = "text-danger" })


            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })

                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

            </div>

            <div class="form-group">

                <input type="submit" value="Log In" class="btn btn-primary " />

            </div>
        </div>
    }
    @Html.ActionLink("Forgot Password?", "ForgotPassword", "Login")
    @*<a href="@Url.Action()" class="forgot-password">Forgot Password?</a>*@
</div>